---
title: Research plan for comparison of missing data handling methods in building variant pathogenicity metapredictors
author: 
- name: "Mikko Särkkä^1,2^"
  affiliation: "^1^Blueprint Genetics Ltd, ^2^University of Eastern Finland"
bibliography: references.bib


...
