apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      serviceAccountName: queue-acc
      containers:
      - name: queue
        image: sgbiodevpipelines.azurecr.io/seagen-azure-aks-queue:5218c29
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"