apiVersion: v1
kind: Pod
metadata:
  name: amiss
spec:
  restartPolicy: Never
  containers:
  - name: amiss-pipeline
    image: bgamiss.azurecr.io/bgamiss:v1
    command: ['sh', '-c', 'sleep 7200']
    env:
      - name: QUEUE_ADDRESS
        value: queue
      - name: QUEUE_NAME
        value: amissqueue
      - name: AZURE_KEY_VAULT_NAME
        valueFrom:
          secretKeyRef:
            name: podconfig
            key: AZURE_KEY_VAULT_NAME
      - name: AZURE_TENANT_ID
        valueFrom:
          secretKeyRef:
            name: podconfig
            key: AZURE_TENANT_ID
      - name: AZURE_MI_CLIENTID
        valueFrom:
          secretKeyRef:
            name: podconfig
            key: AZURE_MI_CLIENTID
    resources:
      limits:
        memory: "40Gi"
        cpu: "1600m"
  tolerations:
  - key: "pipeline"
    operator: "Equal"
    value: "amiss"
    effect: "NoSchedule"
  nodeSelector:
    pipeline: amiss