apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  restartPolicy: Never
  containers:
  - name: stub
    image: bgamiss.azurecr.io/bgamiss:v1
    env:
      - name: QUEUE_ADDRESS
        value: queue:5000
      - name: QUEUE_NAME
        value: demoqueue
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  tolerations:
  - key: "pipeline"
    operator: "Equal"
    value: "demo"
    effect: "NoSchedule"
  nodeSelector:
    pipeline: demo